name: Cumulus 3D Tagcloud
description: This plugins creates and displays a block with a 3d tag cloud. It takes all the tags of the nodes.

author: Israel Segundo
authorEmail: israel.segundo@gmail.com
authorUrl: 
